#!/bin/bash

echo ""
echo "======================================"
echo "✨ Dotfiles installation complete! ✨"
echo "======================================"
echo ""
echo "Next steps:"
echo ""
echo "1. Set up GitHub authentication:"
echo "   $ github-setup"
echo ""
echo "2. If using i3 (Arch Linux):"
echo "   - Log out and select i3 at login screen"
echo "   - Your wallpaper should be at ~/Pictures/wallpaper.jpg"
echo ""
echo "3. For age encryption setup:"
echo "   - Your age key is at ~/.config/age/key.txt"
echo "   - BACKUP THIS KEY SECURELY!"
echo ""
echo "4. Restart your terminal or run:"
echo "   $ source ~/.zshrc"
echo ""
echo "Useful commands:"
echo "  github-setup     - Set up GitHub CLI and SSH keys"
echo "  tmux-sessionizer - Quick project switching (Ctrl+f in terminal)"
echo "  chezmoi update   - Pull and apply latest dotfiles"
echo ""